# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
